### ISSUE TITLE
Scatter.py concat or assign

### ISSUE THREAD

**Issue by DaweiPang32** [sfcta/validation_workbook#20]
For readability and modularity, using concat makes the code easier to understand and maintain. Since the data is small, I think performance is less important.

@chunhochow edits:
referring to code snippets such as:
```py
    # Compute errors
    times = ['Daily', 'AM', 'MD', 'PM', 'EV', 'EA']
    error = {col: est_df[col] - obs_df[col] for col in times}
    error_df = pd.DataFrame(error)
    error_squared_df = error_df.pow(2)
    error_percent_df = error_df.divide(obs_df[times]).fillna(0)
    error_percent_df = error_percent_df.apply(lambda x: x * 100, axis=1)

    # Combine dataframes
    combined_df = pd.concat(
        [est_df, obs_df[times], error_df, error_squared_df, error_percent_df], axis=1)
    Select_time_period_df = combined_df.filter(like=chosen_timeperiod)
    specific_columns_combined_df = combined_df[combined_df_cols]
    Select_time_period_loc_df = pd.concat(
        [specific_columns_combined_df, Select_time_period_df], axis=1)

    # Set column names
    calculation_cols = [
        'Estimated Volume',
        'Observed Volume',
        'Errors',
        'Squared Errors',
        'Percent Errors']
    Select_time_period_loc_df.columns = combined_df_cols + calculation_cols
```

There's also many other cases that use similar logic. Locate them and update all of them in a batch.
        
_Originally posted by @chunhochow in https://github.com/sfcta/validation_workbook/pull/18#discussion_r1712307425_

**Comment by chunhochow** [comment]
I feel that in this case, this is actually less robust and slightly goes against the logic flow. Because these are the creation of columns, not the creation of extra dataframes (which is what the code implies here). The (not-)robustness is especially acute here because column names are set separately after the different columns are concatenated (so if e.g. an extra line/column is inserted the whole thing falls apart unless one carefully checks the logic of the middle code block against the column name setting code block.

It seems to me that, since assign() creates a new dataframe, It wouldn't be a problem to do something like the following (and this would leave the original dataframes unchanged):
```py
select_time_period_[loc_]df = (
    pd.concat([est_df, obs_df[times]], axis=1, keys=["Estimated Volume", "Observed Volume"])  # this is a real concat operation, since these are prexisting dataframes that you're combining. Also, rename the columns immediately here instead of doing it 10 lines later, to reduce the chance of error / cognitive workload
    .assign(  # this ensures that the columns are immediately named as the contents are built
        errors=(est_df[col] - obs_df[col]),
        squared_errors=errors.pow(2),
        ...
    )
```

I'm also fine with:
```py
select_time_period_[loc_]df = pd.concat(...)  # see above
select_time_period_[loc_]df["errors"] = ...   # this also ensures that the columns are immediately named as the contents are built
select_time_period_[loc_]df["squared_errors"] = ...
```
(I hate modifying state in variables since I prefer to program functionally but I can live with this)

But both options seem to me to be better than creating throwaway-dataframes.

**Comment by DaweiPang32** [comment]
I see. thank you for the advice
